name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    contents: read

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}
        name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }} on ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest, windows-latest ]
                php: [ '8.1', '8.2' ]
                symfony: [ '5.4.*', '6.2.*', '6.3.*' ]

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: flex

            -   name: Download dependencies
                env:
                    SYMFONY_REQUIRE: ${{ matrix.symfony }}
                uses: ramsey/composer-install@v1

            -   name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
                run: composer run-script test

            -   name: Upload coverage reports to Codecov
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    verbose: true
                if: matrix.operating-system == 'ubuntu-latest' && matrix.php == '8.1' && matrix.symfony == '5.4.*'
